sudo: required
language: java
jdk: oraclejdk8
services:
  - docker
script:
  - gradle clean
  - gradle wrapper
  - ./gradlew build buildDocker --info

after_success:
- docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
  docker push umasuo/config;
  docker push umasuo/customer-authentication;
  docker push umasuo/customer-info;
  docker push umasuo/device-info;
  docker push umasuo/file-service;
  docker push umasuo/message-pusher;
  docker push umasuo/wechat;
