version: "2.1"
services:
  eva-data:
    image: evacloud/postgres:0.3
    environment:
      POSTGRES_PASSWORD: root
  redis:
    image: redis
    ports:
      - 6379:6379
  message-broker:
    image: umasuo/message-broker:1.1
    ports:
      - 1883:1883
      - 18083:18083
    links:
      - redis
    environment:
      - EMQ_LISTENER_TCP_EXTERNAL=1883
      - EMQ_MQTT_ALLOW_ANOYMOUS=false
      - EMQ_LOADED_PLUGINS="emq_auth_redis,emq_recon,emq_modules,emq_retainer,emq_dashboard"
      - EMQ_AUTH_REDIS_SERVER="redis:6379"
      - EMQ_AUTH_REDIS_PASSWORD_HASH=plain
  config:
    image: reactivesw/config:0.0.1
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=davis.dai@go6d.com
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=davis@go6d
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/umasuo/config-files
      - SERVER_PORT=80
    healthcheck:
      test: "exit 0"
  data-definition:
    image: evacloud/data-definition:0.1
    links: 
      - redis
      - eva-data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eva-data/data_definition
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=80
      - DEVELOPER_SERVICE_URI=http://developer/
  data-center:
    image: evacloud/data-center:0.2
    links:
      - redis
      - eva-data
      - message-broker:mqtt
      - device
      - data-definition
    environment:
      - DEVICE_CENTER_SERVICE_URL=http://device/
      - DATA_DEFINITION_SERVICE_URL=http://data-definition/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eva-data/data_center
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - MESSAGE_BROKER_HOST=mqtt
      - MESSAGE_BROKER_PORT=1883
      - MESSAGE_BROKER_USERNAME=umasuo
      - MESSAGE_BROKER_PASSWORD=password
      - SERVER_PORT=80
  developer:
    image: umasuo/developer:0.1
    dns: 8.8.8.8
    links:
      - redis
      - eva-data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eva-data/developer
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=80
      - SPRING_MAIL_USERNAME=wuyue.xc@gmail.com
      - SPRING_MAIL_PASSWORD=xctll0515
  device:
    image: umasuo/device-center:0.2
    links:
      - redis
      - eva-data
      - message-broker:mqtt
    environment:
      - DATA_DEFINITION_SERVICE_URL=http://data-definition/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eva-data/device_center
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - MESSAGE_BROKER_HOST=mqtt
      - MESSAGE_BROKER_PORT=1883
      - MESSAGE_BROKER_USERNAME=umasuo
      - MESSAGE_BROKER_PASSWORD=password
      - SERVER_PORT=80
  product:
    image: evacloud/product:0.3
    links:
      - redis
      - eva-data
      - developer
      - data-definition
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eva-data/product
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=80
      - DEVELOPER_SERVICE_URI=http://developer/
      - DATADEFINITION_SERVICE_URI=http://data-definition/data-definitions/
  user:
    image: evacloud/user:0.2
    links:
      - redis
      - eva-data
      - developer
      - device
      - message-broker:mqtt
    environment:
      - SERVER_PORT=80
      - DEVICE_SERVICE_URL=http://device/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eva-data/users
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - MESSAGE_BROKER_HOST=mqtt
      - MESSAGE_BROKER_PORT=1883
      - MESSAGE_BROKER_USERNAME=umasuo
      - MESSAGE_BROKER_PASSWORD=password
  feedback:
    image: umasuo/feedback:0.1
    links:
      - eva-data
    environment:
      - SERVER_PORT=80
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eva-data/feedback
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
  report:
    image: umasuo/report:0.1
    links:
      - eva-data
      - device
      # - user
    environment:
      - SERVER_PORT=80
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eva-data/report
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      # - USER_SERVICE_URL=http://user/
      - DEVICE_CENTER_SERVICE_URL=http://device/
  api-gateway-developer:
    image: evacloud/api-gateway-developer:0.2
    ports:
      - 8889:8889
    depends_on:
      config:
        condition: service_healthy
    links:
      - config
      - developer
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config
  # api-gateway-user:
  #   image: umasuo/api-gateway-user:0.1
  #   ports:
  #     - 8887:8887
  #   depends_on:
  #     config:
  #       condition: service_healthy
  #   links:
  #     - config
  #     - user
  #   environment:
  #     - SPRING_CLOUD_CONFIG_URI=http://config