kind: List
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: eva-config
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: eva-config
      spec:
        containers:
        - name: eva-config
          image: reactivesw/config:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: spring_cloud_config_server_git_username
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: github.username
          - name: spring_cloud_config_server_git_password
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: github.password
          - name: spring_cloud_config_server_git_uri
            value: https://github.com/umasuo/config-files
          - name: server_port
            value: "80"
- kind: Service
  apiVersion: v1
  metadata:
    name: eva-config
    labels:
      name: eva-config
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30128
    selector:
      name: eva-config