kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: developer
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: developer
      spec:
        containers:
        - name: developer
          image: evacloud/developer:0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: server_port
            value: "80"
          - name: spring_cloud_config_uri
            value: http://eva-config
          - name: user_service_uri
            value: http://user/
          - name: product_service_uri
            value: http://product/
          - name: spring_datasource_url
            value: jdbc:postgresql://eva-data/developer
          - name: spring_redis_host
            value: redis
          - name: spring_datasource_username
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: postgres.username
          - name: spring_datasource_password
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: postgres.password
          - name: jwt_secret
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: jwt.secret
          - name: spring_mail_username
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: email
          - name: spring_mail_password
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: email.password
- kind: Service
  apiVersion: v1
  metadata:
    name: developer
    labels:
      name: developer
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30104
    selector:
      name: developer