kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: message-broker
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: message-broker
      spec:
        containers:
        - name: message-broker
          image: umasuo/message-broker:1.1
          imagePullPolicy: Always
          ports:
          - containerPort: 1883
          - containerPort: 18083
          env:
          - name: emq_listener__tcp__external
            value: '1883'
          - name: emq_mqtt_allow_anonymous
            value: 'false'
          - name: emq_loaded_plugins
            value: emq_auth_redis,emq_recon,emq_modules,emq_retainer,emq_dashboard
          - name: emq_auth_redis_server
            value: redis
          - name: emq_auth_redis_password_hash
            value: plain
- kind: Service
  apiVersion: v1
  metadata:
    name: message-broker
    labels:
      name: message-broker
  spec:
    type: LoadBalancer
    ports:
    - name: broker
      port: 1883
      targetPort: 1883
      nodePort: 30132
    - name: dashboard
      port: 18083
      targetPort: 18083
      nodePort: 30133
    selector:
      name: message-broker