apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pg-data
  labels:
    name: pg-data
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pg-data
    spec:
      containers:
      - name: pg-data
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reactivesw-secret
              key: postgres.password