kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: user
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: user
      spec:
        containers:
        - name: user
          image: evacloud/user:0.2
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: server_port
            value: "80"
          - name: spring_cloud_config_uri
            value: http://eva-config
          - name: device_service_url
            value: http://device/
          - name: spring_datasource_url
            value: jdbc:postgresql://eva-data/users
          - name: spring_redis_host
            value: redis
          - name: spring_datasource_username
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: postgres.username
          - name: spring_datasource_password
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: postgres.password
          - name: jwt_secret
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: jwt.secret
          - name: message_broker_host
            value: message-broker
          - name: message_broker_port
            value: '1883'
          - name: message_broker_username
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: user.broker.username
          - name: message_broker_password
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: user.broker.password
          - name: sms_yunpian_key
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: sms.yunpian.key
- kind: Service
  apiVersion: v1
  metadata:
    name: user
    labels:
      name: user
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30109
    selector:
      name: user