kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: device
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: device
      spec:
        containers:
        - name: device
          image: umasuo/device-center:0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: server_port
            value: "80"
          - name: spring_cloud_config_uri
            value: http://eva-config
          - name: spring_datasource_url
            value: jdbc:postgresql://eva-data/device_center
          - name: spring_redis_host
            value: redis
          - name: spring_datasource_username
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: postgres.username
          - name: spring_datasource_password
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: postgres.password
          - name: jwt_secret
            valueFrom:
              secretKeyRef:
                name: eva-secret
                key: jwt.secret
          - name: message_broker_host
            value: message-broker
          - name: message_broker_port
            value: '1883'
          - name: message_broker_username
            value: umasuo
          - name: message_broker_password
            value: password
- kind: Service
  apiVersion: v1
  metadata:
    name: device
    labels:
      name: device
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30106
    selector:
      name: device